C:\Python27\python.exe wtxt-wiki.py genHtml index.txt
C:\Python27\python.exe wtxt-wiki.py genHtml 2-overview.txt
C:\Python27\python.exe wtxt-wiki.py genHtml 3-modgroups.txt
C:\Python27\python.exe wtxt-wiki.py genHtml 4-conflict-detection-and-resolution.txt
C:\Python27\python.exe wtxt-wiki.py genHtml 5-mod-cleaning-and-error-checking.txt
C:\Python27\python.exe wtxt-wiki.py genHtml 6-managing-mod-files.txt
C:\Python27\python.exe wtxt-wiki.py genHtml 7-mod-utilities.txt
C:\Python27\python.exe wtxt-wiki.py genHtml 8-fo3edit-faq.txt
C:\Python27\python.exe wtxt-wiki.py genHtml 9-appendix.txt
C:\Python27\python.exe wtxt-wiki.py genHtml 10-cheat-sheets-and-quick-reference-charts.txt
C:\Python27\python.exe wtxt-wiki.py genHtml 12-Scripting-Resources.txt
C:\Python27\python.exe wtxt-wiki.py genHtml 13-tutorials.txt
