C:\Python38-64\python.exe wtxt-wiki.py genHtml index.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 2-overview.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 3-basicuse.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 4-modgroups.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 5-conflict-detection-and-resolution.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 6-themethod.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 6-mod-cleaning-and-error-checking.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 7-mod-cleaning-and-error-checking.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 8-managing-mod-files.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 9-mod-utilities.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 10-fo3edit-faq.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 11-appendix.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 12-cheat-sheets-and-quick-reference-charts.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 13-Scripting-Functions.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 14-Scripting-Resources.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 15-tutorials.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 16-xLODGen.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml 17-DynDoLod.txt
C:\Python38-64\python.exe wtxt-wiki.py genHtml whatsnew.md
